// In-memory Mock Database generated from Excel workbooks in tai_lieu/
// Generated on: 2026-06-14 13:55:14
// Serves as the mock database for local API Console testing.

const lessons = [
    {
        "id":  1,
        "title":  "Bài 1: Hajimemashite",
        "description":  "Bai hoc tu dong nhap tu tep Bai1_Hajimemashite.xlsx"
    },
    {
        "id":  2,
        "title":  "Bài 2: KorewaJishoDesu",
        "description":  "Bai hoc tu dong nhap tu tep Bai2_KorewaJishoDesu.xlsx"
    }
];

const vocabulary = [
    {
        "id":  1,
        "lesson_id":  1,
        "hiragana":  "わたし",
        "romaji":  "watashi",
        "vietnamese_meaning":  "Tôi",
        "word_type":  "pronoun",
        "japanese_example":  "私は ミラー です。",
        "example_meaning":  "Tôi là Miller.",
        "mnemonic_tip":  "Mẹo nhớ: Liên tưởng \u0027hoa ta đi\u0027 - Tôi đi hái hoa của ta.",
        "image_url":  ""
    },
    {
        "id":  2,
        "lesson_id":  1,
        "hiragana":  "あなた",
        "romaji":  "anata",
        "vietnamese_meaning":  "Bạn / Anh / Chị",
        "word_type":  "pronoun",
        "japanese_example":  "あなたは 学生 ですか。",
        "example_meaning":  "Bạn là học sinh phải không?",
        "mnemonic_tip":  "Mẹo nhớ: \u0027A, na ta\u0027 - À, nãy ta nói chuyện với Bạn.",
        "image_url":  ""
    },
    {
        "id":  3,
        "lesson_id":  1,
        "hiragana":  "あのひと",
        "romaji":  "ano hito",
        "vietnamese_meaning":  "Người kia / Người đó",
        "word_type":  "pronoun",
        "japanese_example":  "あの人は だれ ですか。",
        "example_meaning":  "Người kia là ai vậy?",
        "mnemonic_tip":  "Mẹo nhớ: \u0027À, nó hí ta\u0027 - Người kia đang hí hửng nhìn ta.",
        "image_url":  ""
    },
    {
        "id":  4,
        "lesson_id":  1,
        "hiragana":  "あのかた",
        "romaji":  "ano kata",
        "vietnamese_meaning":  "Vị kia (kính ngữ)",
        "word_type":  "pronoun",
        "japanese_example":  "あの方は どなた ですか。",
        "example_meaning":  "Vị kia là vị nào vậy?",
        "mnemonic_tip":  "Mẹo nhớ: \u0027À, nó ca ta\u0027 - Vị kia đang ca ngợi ta.",
        "image_url":  ""
    },
    {
        "id":  5,
        "lesson_id":  1,
        "hiragana":  "せんせい",
        "romaji":  "sensei",
        "vietnamese_meaning":  "Giáo viên / Thầy cô",
        "word_type":  "noun",
        "japanese_example":  "ワットさんは 先生 です。",
        "example_meaning":  "Ông Watt là giáo viên.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Sên sấy\u0027 - Thầy giáo sấy con sên trên bảng.",
        "image_url":  ""
    },
    {
        "id":  6,
        "lesson_id":  1,
        "hiragana":  "きょうし",
        "romaji":  "kyoushi",
        "vietnamese_meaning":  "Nhà giáo (chỉ nghề nghiệp)",
        "word_type":  "noun",
        "japanese_example":  "私は 教師 です。",
        "example_meaning":  "Tôi là nhà giáo.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Kiêu sĩ\u0027 - Người nhà giáo không được kiêu ngạo.",
        "image_url":  ""
    },
    {
        "id":  7,
        "lesson_id":  1,
        "hiragana":  "がくせい",
        "romaji":  "gakusei",
        "vietnamese_meaning":  "Học sinh / Sinh viên",
        "word_type":  "noun",
        "japanese_example":  "サントスさんは 学生 です。",
        "example_meaning":  "Anh Santos là sinh viên.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Gác sấy\u0027 - Học sinh gác sách đem đi sấy.",
        "image_url":  ""
    },
    {
        "id":  8,
        "lesson_id":  1,
        "hiragana":  "かいしゃいん",
        "romaji":  "kaishain",
        "vietnamese_meaning":  "Nhân viên công ty",
        "word_type":  "noun",
        "japanese_example":  "ミラーさんは 会社員 です。",
        "example_meaning":  "Anh Miller là nhân viên công ty.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Kai\u0027 (gặp) + \u0027sha\u0027 (xã hội) + \u0027in\u0027 (thành viên).",
        "image_url":  ""
    },
    {
        "id":  9,
        "lesson_id":  1,
        "hiragana":  "しゃいん",
        "romaji":  "shain",
        "vietnamese_meaning":  "Nhân viên (công ty cụ thể)",
        "word_type":  "noun",
        "japanese_example":  "私は IMCの 社員 です。",
        "example_meaning":  "Tôi là nhân viên của công ty IMC.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Sa in\u0027 - Nhân viên bị sa thải vì in ấn sai tài liệu.",
        "image_url":  ""
    },
    {
        "id":  10,
        "lesson_id":  1,
        "hiragana":  "ぎんこういん",
        "romaji":  "ginkouin",
        "vietnamese_meaning":  "Nhân viên ngân hàng",
        "word_type":  "noun",
        "japanese_example":  "山川さんは 銀行員 です。",
        "example_meaning":  "Anh Yamakawa là nhân viên ngân hàng.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Gìn của in\u0027 - Nhân viên gìn giữ của cải in ra ở ngân hàng.",
        "image_url":  ""
    },
    {
        "id":  11,
        "lesson_id":  1,
        "hiragana":  "いしゃ",
        "romaji":  "isha",
        "vietnamese_meaning":  "Bác sĩ",
        "word_type":  "noun",
        "japanese_example":  "あの人は 医者 です。",
        "example_meaning":  "Người kia là bác sĩ.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Y xá\u0027 - Bác sĩ ở y xá chữa bệnh.",
        "image_url":  ""
    },
    {
        "id":  12,
        "lesson_id":  1,
        "hiragana":  "けんきゅうしゃ",
        "romaji":  "kenkyuusha",
        "vietnamese_meaning":  "Nhà nghiên cứu",
        "word_type":  "noun",
        "japanese_example":  "イーさんは 研究者 です。",
        "example_meaning":  "Anh Lee là nhà nghiên cứu.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Kén cự xá\u0027 - Nhà nghiên cứu kén chọn ký túc xá.",
        "image_url":  ""
    },
    {
        "id":  13,
        "lesson_id":  1,
        "hiragana":  "エンジニア",
        "romaji":  "enjinia",
        "vietnamese_meaning":  "Kỹ sư",
        "word_type":  "noun",
        "japanese_example":  "ワンさんは エンジニア です。",
        "example_meaning":  "Anh Wang là kỹ sư.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Em dí bia\u0027 - Kỹ sư công trình bắt em dí ly bia.",
        "image_url":  ""
    },
    {
        "id":  14,
        "lesson_id":  1,
        "hiragana":  "だいがく",
        "romaji":  "daigaku",
        "vietnamese_meaning":  "Trường đại học",
        "word_type":  "noun",
        "japanese_example":  "ここは さくら 大学 です。",
        "example_meaning":  "Đây là trường đại học Sakura.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Đại gác\u0027 - Trường đại học có cái gác lớn.",
        "image_url":  ""
    },
    {
        "id":  15,
        "lesson_id":  1,
        "hiragana":  "びょういん",
        "romaji":  "byouin",
        "vietnamese_meaning":  "Bệnh viện",
        "word_type":  "noun",
        "japanese_example":  "あそこは 神戸 病院 です。",
        "example_meaning":  "Chỗ kia là bệnh viện Kobe.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Biu in\u0027 - Bệnh viện in bill tiền thuốc.",
        "image_url":  ""
    },
    {
        "id":  16,
        "lesson_id":  1,
        "hiragana":  "でんき",
        "romaji":  "denki",
        "vietnamese_meaning":  "Điện / Bóng đèn / Công ty điện",
        "word_type":  "noun",
        "japanese_example":  "パワー 電気の 社員 です。",
        "example_meaning":  "Là nhân viên của công ty Điện lực Power.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Đèn kỳ\u0027 - Bóng đèn này kỳ lạ, lúc sáng lúc tắt.",
        "image_url":  ""
    },
    {
        "id":  17,
        "lesson_id":  1,
        "hiragana":  "だれ",
        "romaji":  "dare",
        "vietnamese_meaning":  "Ai (Hỏi người)",
        "word_type":  "pronoun",
        "japanese_example":  "あの人は 誰 ですか。",
        "example_meaning":  "Người kia là ai?",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Da dê\u0027 - Ai lấy da dê của tôi?",
        "image_url":  ""
    },
    {
        "id":  18,
        "lesson_id":  1,
        "hiragana":  "どなた",
        "romaji":  "donata",
        "vietnamese_meaning":  "Vị nào (kính ngữ)",
        "word_type":  "pronoun",
        "japanese_example":  "あの方は どなた ですか。",
        "example_meaning":  "Vị kia là vị nào vậy?",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Đô na ta\u0027 - Vị nào cho ta tiền đô la?",
        "image_url":  ""
    },
    {
        "id":  19,
        "lesson_id":  1,
        "hiragana":  "さい",
        "romaji":  "sai",
        "vietnamese_meaning":  "...tuổi",
        "word_type":  "noun",
        "japanese_example":  "私は 28 歳 です。",
        "example_meaning":  "Tôi 28 tuổi.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Sai\u0027 - Đếm tuổi sai rồi bạn ơi.",
        "image_url":  ""
    },
    {
        "id":  20,
        "lesson_id":  1,
        "hiragana":  "なんさい",
        "romaji":  "nansai",
        "vietnamese_meaning":  "Mấy tuổi / Bao nhiêu tuổi",
        "word_type":  "pronoun",
        "japanese_example":  "お子さんは 何歳 ですか。",
        "example_meaning":  "Con của bạn mấy tuổi rồi?",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Nản sai\u0027 - Hỏi tuổi hoài nản ghê.",
        "image_url":  ""
    },
    {
        "id":  21,
        "lesson_id":  1,
        "hiragana":  "はい",
        "romaji":  "hai",
        "vietnamese_meaning":  "Vâng / Dạ",
        "word_type":  "greeting",
        "japanese_example":  "はい、そうです。",
        "example_meaning":  "Vâng, đúng vậy.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Hai\u0027 - Vâng, có hai cái.",
        "image_url":  ""
    },
    {
        "id":  22,
        "lesson_id":  1,
        "hiragana":  "いいえ",
        "romaji":  "iie",
        "vietnamese_meaning":  "Không / Không phải",
        "word_type":  "greeting",
        "japanese_example":  "いいえ、そうじゃありません。",
        "example_meaning":  "Không, không phải vậy.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Y y\u0027 - Không, đừng y y chủ quan thế.",
        "image_url":  ""
    },
    {
        "id":  23,
        "lesson_id":  1,
        "hiragana":  "はじめまして",
        "romaji":  "hajimemashite",
        "vietnamese_meaning":  "Rất vui được gặp bạn",
        "word_type":  "greeting",
        "japanese_example":  "初めまして、ミラー です。",
        "example_meaning":  "Rất vui được gặp bạn, tôi là Miller.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Hà giờ mê má chị\u0027 - Lần đầu gặp đã chào hỏi mê luôn.",
        "image_url":  ""
    },
    {
        "id":  24,
        "lesson_id":  1,
        "hiragana":  "からきました",
        "romaji":  "kara kimashita",
        "vietnamese_meaning":  "Đến từ...",
        "word_type":  "greeting",
        "japanese_example":  "ベトナム から来ました。",
        "example_meaning":  "Tôi đến từ Việt Nam.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Cá ra ký tá\u0027 - Đến từ vùng biển xa xôi.",
        "image_url":  ""
    },
    {
        "id":  25,
        "lesson_id":  1,
        "hiragana":  "どうぞよろしく",
        "romaji":  "douzo yoroshiku",
        "vietnamese_meaning":  "Rất mong được sự giúp đỡ",
        "word_type":  "greeting",
        "japanese_example":  "どうぞよろしくお願いします。",
        "example_meaning":  "Rất mong nhận được sự giúp đỡ.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Đỗ rổ vô lịch\u0027 - Rất mong được giúp đỡ xếp rổ đỗ lịch sự.",
        "image_url":  ""
    },
    {
        "id":  26,
        "lesson_id":  1,
        "hiragana":  "しつれいですが",
        "romaji":  "shitsurei desuga",
        "vietnamese_meaning":  "Xin lỗi (khi hỏi chuyện riêng tư)",
        "word_type":  "greeting",
        "japanese_example":  "失礼ですが、お名前は？",
        "example_meaning":  "Xin lỗi, tên bạn là gì?",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Sứt răng đi gà\u0027 - Xin lỗi nha, đi nha sĩ vì sứt răng.",
        "image_url":  ""
    },
    {
        "id":  27,
        "lesson_id":  1,
        "hiragana":  "おnaまえは",
        "romaji":  "onamae wa",
        "vietnamese_meaning":  "Tên bạn là gì?",
        "word_type":  "greeting",
        "japanese_example":  "お名前は 何ですか。",
        "example_meaning":  "Tên của bạn là gì?",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Ổ nằm đây\u0027 - Xin hỏi tên bạn nằm ở đâu?",
        "image_url":  ""
    },
    {
        "id":  28,
        "lesson_id":  1,
        "hiragana":  "こちら",
        "romaji":  "kochira",
        "vietnamese_meaning":  "Đây là / Vị này là",
        "word_type":  "pronoun",
        "japanese_example":  "こちらは ミラーさん です。",
        "example_meaning":  "Đây là anh Miller.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Cô chia ra\u0027 - Vị này là người cô chia quà cho.",
        "image_url":  ""
    },
    {
        "id":  29,
        "lesson_id":  1,
        "hiragana":  "アメリカ",
        "romaji":  "amerika",
        "vietnamese_meaning":  "Nước Mỹ",
        "word_type":  "noun",
        "japanese_example":  "アメリカ からきました。",
        "example_meaning":  "Tôi đến từ nước Mỹ.",
        "mnemonic_tip":  "Âm tương tự America.",
        "image_url":  ""
    },
    {
        "id":  30,
        "lesson_id":  1,
        "hiragana":  "イギリス",
        "romaji":  "igirisu",
        "vietnamese_meaning":  "Nước Anh",
        "word_type":  "noun",
        "japanese_example":  "イギリス人 です。",
        "example_meaning":  "Tôi là người Anh.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Y ghi lịch\u0027 - Nước Anh ghi lịch sử y học.",
        "image_url":  ""
    },
    {
        "id":  31,
        "lesson_id":  1,
        "hiragana":  "インド",
        "romaji":  "indo",
        "vietnamese_meaning":  "Nước Ấn Độ",
        "word_type":  "noun",
        "japanese_example":  "インドから 来ました。",
        "example_meaning":  "Đến từ Ấn Độ.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027In đô\u0027 - Ấn Độ tự in tiền đô la.",
        "image_url":  ""
    },
    {
        "id":  32,
        "lesson_id":  1,
        "hiragana":  "インドネシア",
        "romaji":  "indoneshia",
        "vietnamese_meaning":  "Nước Indonesia",
        "word_type":  "noun",
        "japanese_example":  "インドネシア人 です。",
        "example_meaning":  "Tôi là người Indonesia.",
        "mnemonic_tip":  "Âm tương tự Indonesia.",
        "image_url":  ""
    },
    {
        "id":  33,
        "lesson_id":  1,
        "hiragana":  "かんこく",
        "romaji":  "kankoku",
        "vietnamese_meaning":  "Nước Hàn Quốc",
        "word_type":  "noun",
        "japanese_example":  "韓国 から来ました。",
        "example_meaning":  "Đến từ Hàn Quốc.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Canh cốc\u0027 - Người Hàn Quốc thích ăn canh bằng cốc.",
        "image_url":  ""
    },
    {
        "id":  34,
        "lesson_id":  1,
        "hiragana":  "タイ",
        "romaji":  "tai",
        "vietnamese_meaning":  "Nước Thái Lan",
        "word_type":  "noun",
        "japanese_example":  "タイ人 です。",
        "example_meaning":  "Tôi là người Thái Lan.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Tay\u0027 - Người Thái Lan múa tay dẻo dai.",
        "image_url":  ""
    },
    {
        "id":  35,
        "lesson_id":  1,
        "hiragana":  "ちゅうごく",
        "romaji":  "chuugoku",
        "vietnamese_meaning":  "Nước Trung Quốc",
        "word_type":  "noun",
        "japanese_example":  "中国 から来ました。",
        "example_meaning":  "Tôi đến từ Trung Quốc.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Chung gốc\u0027 - Trung Quốc và Nhật Bản chung gốc chữ Hán.",
        "image_url":  ""
    },
    {
        "id":  36,
        "lesson_id":  1,
        "hiragana":  "ドイツ",
        "romaji":  "doitsu",
        "vietnamese_meaning":  "Nước Đức",
        "word_type":  "noun",
        "japanese_example":  "ドイツの 車 です。",
        "example_meaning":  "Xe hơi của nước Đức.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Đôi giày\u0027 - Nước Đức sản xuất đôi giày da rất bền.",
        "image_url":  ""
    },
    {
        "id":  37,
        "lesson_id":  1,
        "hiragana":  "にほん",
        "romaji":  "nihon",
        "vietnamese_meaning":  "Nước Nhật Bản",
        "word_type":  "noun",
        "japanese_example":  "日本 から来ました。",
        "example_meaning":  "Tôi đến từ Nhật Bản.",
        "mnemonic_tip":  "Mẹo nhớ: \u0027Đi hôn\u0027 - Sang Nhật Bản đi hôn mọi người.",
        "image_url":  ""
    },
    {
        "id":  38,
        "lesson_id":  1,
        "hiragana":  "フランス",
        "romaji":  "furansu",
        "vietnamese_meaning":  "Nước Pháp",
        "word_type":  "noun",
        "japanese_example":  "フランス からきました。",
        "example_meaning":  "Tôi đến từ Pháp.",
        "mnemonic_tip":  "Âm tương tự France.",
        "image_url":  ""
    },
    {
        "id":  39,
        "lesson_id":  1,
        "hiragana":  "ブラジル",
        "romaji":  "burajiru",
        "vietnamese_meaning":  "Nước Brazil",
        "word_type":  "noun",
        "japanese_example":  "ブラジル人 です。",
        "example_meaning":  "Tôi là người Brazil.",
        "mnemonic_tip":  "Âm tương tự Brazil.",
        "image_url":  ""
    },
    {
        "id":  40,
        "lesson_id":  1,
        "hiragana":  "ベトナム",
        "romaji":  "betonamu",
        "vietnamese_meaning":  "Nước Việt Nam",
        "word_type":  "noun",
        "japanese_example":  "ベトナム からきました。",
        "example_meaning":  "Tôi đến từ Việt Nam.",
        "mnemonic_tip":  "Đồng âm Việt Nam.",
        "image_url":  ""
    },
    {
        "id":  41,
        "lesson_id":  2,
        "hiragana":  "これ",
        "romaji":  "kore",
        "vietnamese_meaning":  "đây, cái này",
        "word_type":  "pronoun",
        "japanese_example":  "これは辞書です。",
        "example_meaning":  "Đây là từ điển.",
        "mnemonic_tip":  "Chỉ vật gần người nói",
        "image_url":  ""
    },
    {
        "id":  42,
        "lesson_id":  2,
        "hiragana":  "それ",
        "romaji":  "sore",
        "vietnamese_meaning":  "đó, cái đó",
        "word_type":  "pronoun",
        "japanese_example":  "それは何ですか。",
        "example_meaning":  "Đó là cái gì thế?",
        "mnemonic_tip":  "Chỉ vật gần người nghe",
        "image_url":  ""
    },
    {
        "id":  43,
        "lesson_id":  2,
        "hiragana":  "あれ",
        "romaji":  "are",
        "vietnamese_meaning":  "kia, cái kia",
        "word_type":  "pronoun",
        "japanese_example":  "あれは私の傘です。",
        "example_meaning":  "Kia là cái ô của tôi.",
        "mnemonic_tip":  "Chỉ vật xa cả hai người",
        "image_url":  ""
    },
    {
        "id":  44,
        "lesson_id":  2,
        "hiragana":  "この",
        "romaji":  "kono",
        "vietnamese_meaning":  "~ này",
        "word_type":  "pronoun",
        "japanese_example":  "この本は山田さんのです。",
        "example_meaning":  "Quyển sách này là của Yamada.",
        "mnemonic_tip":  "Chỉ định từ đi trước danh từ, gần người nói",
        "image_url":  ""
    },
    {
        "id":  45,
        "lesson_id":  2,
        "hiragana":  "その",
        "romaji":  "sono",
        "vietnamese_meaning":  "~ đó",
        "word_type":  "pronoun",
        "japanese_example":  "その鍵は私のです。",
        "example_meaning":  "Chiếc chìa khóa đó là của tôi.",
        "mnemonic_tip":  "Chỉ định từ đi trước danh từ, gần người nghe",
        "image_url":  ""
    },
    {
        "id":  46,
        "lesson_id":  2,
        "hiragana":  "あの",
        "romaji":  "ano",
        "vietnamese_meaning":  "~ kia",
        "word_type":  "pronoun",
        "japanese_example":  "あの車は誰のですか。",
        "example_meaning":  "Chiếc ô tô kia là của ai?",
        "mnemonic_tip":  "Chỉ định từ đi trước danh từ, xa cả hai",
        "image_url":  ""
    },
    {
        "id":  47,
        "lesson_id":  2,
        "hiragana":  "ほん",
        "romaji":  "hon",
        "vietnamese_meaning":  "sách",
        "word_type":  "noun",
        "japanese_example":  "これは日本語の本です。",
        "example_meaning":  "Đây là sách tiếng Nhật.",
        "mnemonic_tip":  "本 - Bản",
        "image_url":  ""
    },
    {
        "id":  48,
        "lesson_id":  2,
        "hiragana":  "じしょ",
        "romaji":  "jisho",
        "vietnamese_meaning":  "từ điển",
        "word_type":  "noun",
        "japanese_example":  "これは辞書です。",
        "example_meaning":  "Đây là từ điển.",
        "mnemonic_tip":  "辞書 - Từ thư",
        "image_url":  ""
    },
    {
        "id":  49,
        "lesson_id":  2,
        "hiragana":  "ざっし",
        "romaji":  "zasshi",
        "vietnamese_meaning":  "tạp chí",
        "word_type":  "noun",
        "japanese_example":  "その雑誌は面白いです。",
        "example_meaning":  "Quyển tạp chí đó thú vị.",
        "mnemonic_tip":  "雑誌 - Tạp chí",
        "image_url":  ""
    },
    {
        "id":  50,
        "lesson_id":  2,
        "hiragana":  "しんぶん",
        "romaji":  "shinbun",
        "vietnamese_meaning":  "báo",
        "word_type":  "noun",
        "japanese_example":  "毎日新聞を読みます。",
        "example_meaning":  "Mỗi ngày tôi đều đọc báo.",
        "mnemonic_tip":  "新聞 - Tân văn",
        "image_url":  ""
    },
    {
        "id":  51,
        "lesson_id":  2,
        "hiragana":  "のーt",
        "romaji":  "nōto",
        "vietnamese_meaning":  "vở, sổ tay",
        "word_type":  "noun",
        "japanese_example":  "これは私のノートです。",
        "example_meaning":  "Đây là vở của tôi.",
        "mnemonic_tip":  "Vở ghi chép",
        "image_url":  ""
    },
    {
        "id":  52,
        "lesson_id":  2,
        "hiragana":  "てちょう",
        "romaji":  "techō",
        "vietnamese_meaning":  "sổ tay",
        "word_type":  "noun",
        "japanese_example":  "手帳に予定を書きます。",
        "example_meaning":  "Tôi viết lịch trình vào sổ tay.",
        "mnemonic_tip":  "手帳 - Thủ trướng",
        "image_url":  ""
    },
    {
        "id":  53,
        "lesson_id":  2,
        "hiragana":  "めいし",
        "romaji":  "meishi",
        "vietnamese_meaning":  "danh thiếp",
        "word_type":  "noun",
        "japanese_example":  "名刺を交換します。",
        "example_meaning":  "Chúng tôi trao đổi danh thiếp.",
        "mnemonic_tip":  "名刺 - Danh thứ",
        "image_url":  ""
    },
    {
        "id":  54,
        "lesson_id":  2,
        "hiragana":  "かーど",
        "romaji":  "kādo",
        "vietnamese_meaning":  "thẻ, card",
        "word_type":  "noun",
        "japanese_example":  "これはクレジットカードです。",
        "example_meaning":  "Đây là thẻ tín dụng.",
        "mnemonic_tip":  "Thẻ nhựa",
        "image_url":  ""
    },
    {
        "id":  55,
        "lesson_id":  2,
        "hiragana":  "えんpiつ",
        "romaji":  "enpitsu",
        "vietnamese_meaning":  "bút chì",
        "word_type":  "noun",
        "japanese_example":  "鉛筆で名前を書きます。",
        "example_meaning":  "Tôi viết tên bằng bút chì.",
        "mnemonic_tip":  "鉛筆 - Duyên bút",
        "image_url":  ""
    },
    {
        "id":  56,
        "lesson_id":  2,
        "hiragana":  "ぼーるぺん",
        "romaji":  "bōrupen",
        "vietnamese_meaning":  "bút bi",
        "word_type":  "noun",
        "japanese_example":  "ボールペンで書きます。",
        "example_meaning":  "Tôi viết bằng bút bi.",
        "mnemonic_tip":  "Bút bi nước",
        "image_url":  ""
    },
    {
        "id":  57,
        "lesson_id":  2,
        "hiragana":  "しゃーpぺんしる",
        "romaji":  "shāpupenshiru",
        "vietnamese_meaning":  "bút chì kim",
        "word_type":  "noun",
        "japanese_example":  "シャープペンシルは便利です。",
        "example_meaning":  "Bút chì kim thì tiện lợi.",
        "mnemonic_tip":  "Chì bấm",
        "image_url":  ""
    },
    {
        "id":  58,
        "lesson_id":  2,
        "hiragana":  "かぎ",
        "romaji":  "kagi",
        "vietnamese_meaning":  "chìa khóa",
        "word_type":  "noun",
        "japanese_example":  "車の鍵をなくしました。",
        "example_meaning":  "Tôi mất chìa khóa ô tô rồi.",
        "mnemonic_tip":  "鍵 - Kiện",
        "image_url":  ""
    },
    {
        "id":  59,
        "lesson_id":  2,
        "hiragana":  "とけい",
        "romaji":  "tokei",
        "vietnamese_meaning":  "đồng hồ",
        "word_type":  "noun",
        "japanese_example":  "あの時計は高いです。",
        "example_meaning":  "Cái đồng hồ kia đắt tiền.",
        "mnemonic_tip":  "時計 - Thời kế",
        "image_url":  ""
    },
    {
        "id":  60,
        "lesson_id":  2,
        "hiragana":  "かsa",
        "romaji":  "kasa",
        "vietnamese_meaning":  "ô, dù",
        "word_type":  "noun",
        "japanese_example":  "雨ですから、傘を貸します。",
        "example_meaning":  "Vì trời mưa nên tôi cho mượn ô.",
        "mnemonic_tip":  "傘 - Tản",
        "image_url":  ""
    },
    {
        "id":  61,
        "lesson_id":  2,
        "hiragana":  "かban",
        "romaji":  "kaban",
        "vietnamese_meaning":  "cặp sách, túi xách",
        "word_type":  "noun",
        "japanese_example":  "新しい鞄を買いました。",
        "example_meaning":  "Tôi đã mua cái cặp sách mới.",
        "mnemonic_tip":  "鞄 - Cách bản",
        "image_url":  ""
    },
    {
        "id":  62,
        "lesson_id":  2,
        "hiragana":  "しーでぃー",
        "romaji":  "shīdī",
        "vietnamese_meaning":  "đĩa CD",
        "word_type":  "noun",
        "japanese_example":  "CDを聴きます。",
        "example_meaning":  "Tôi nghe đĩa CD.",
        "mnemonic_tip":  "Đĩa nhạc",
        "image_url":  ""
    },
    {
        "id":  63,
        "lesson_id":  2,
        "hiragana":  "てれび",
        "romaji":  "terebi",
        "vietnamese_meaning":  "tivi",
        "word_type":  "noun",
        "japanese_example":  "テレビを見ます。",
        "example_meaning":  "Tôi xem tivi.",
        "mnemonic_tip":  "Thiết bị vô tuyến",
        "image_url":  ""
    },
    {
        "id":  64,
        "lesson_id":  2,
        "hiragana":  "らじお",
        "romaji":  "rajio",
        "vietnamese_meaning":  "đài",
        "word_type":  "noun",
        "japanese_example":  "ラジオを聴きます。",
        "example_meaning":  "Tôi nghe đài radio.",
        "mnemonic_tip":  "Thiết bị phát thanh",
        "image_url":  ""
    },
    {
        "id":  65,
        "lesson_id":  2,
        "hiragana":  "かめら",
        "romaji":  "kamera",
        "vietnamese_meaning":  "máy ảnh",
        "word_type":  "noun",
        "japanese_example":  "カメラで写真を撮ります。",
        "example_meaning":  "Tôi chụp ảnh bằng máy ảnh.",
        "mnemonic_tip":  "Máy ảnh cơ",
        "image_url":  ""
    },
    {
        "id":  66,
        "lesson_id":  2,
        "hiragana":  "こんpiゅーた",
        "romaji":  "konpyūta",
        "vietnamese_meaning":  "máy vi tính",
        "word_type":  "noun",
        "japanese_example":  "コンピュータは新しいです。",
        "example_meaning":  "Máy vi tính thì mới.",
        "mnemonic_tip":  "Máy tính bàn",
        "image_url":  ""
    },
    {
        "id":  67,
        "lesson_id":  2,
        "hiragana":  "じどうsha",
        "romaji":  "jidōsha",
        "vietnamese_meaning":  "ô tô, xe hơi",
        "word_type":  "noun",
        "japanese_example":  "自動車を運転します。",
        "example_meaning":  "Tôi lái xe hơi.",
        "mnemonic_tip":  "自動車 - Tự động xa",
        "image_url":  ""
    },
    {
        "id":  68,
        "lesson_id":  2,
        "hiragana":  "つくえ",
        "romaji":  "tsukue",
        "vietnamese_meaning":  "bàn",
        "word_type":  "noun",
        "japanese_example":  "机の上に本があります。",
        "example_meaning":  "Có quyển sách trên bàn.",
        "mnemonic_tip":  "机 - Kỷ",
        "image_url":  ""
    },
    {
        "id":  69,
        "lesson_id":  2,
        "hiragana":  "いす",
        "romaji":  "isu",
        "vietnamese_meaning":  "ghế",
        "word_type":  "noun",
        "japanese_example":  "椅子に座ります。",
        "example_meaning":  "Tôi ngồi vào ghế.",
        "mnemonic_tip":  "Ghế ngồi",
        "image_url":  ""
    },
    {
        "id":  70,
        "lesson_id":  2,
        "hiragana":  "ちょこれーと",
        "romaji":  "chokorēto",
        "vietnamese_meaning":  "sô-cô-la",
        "word_type":  "noun",
        "japanese_example":  "チョコレートを食べます。",
        "example_meaning":  "Tôi ăn sô-cô-la.",
        "mnemonic_tip":  "Kẹo ngọt",
        "image_url":  ""
    },
    {
        "id":  71,
        "lesson_id":  2,
        "hiragana":  "こーひー",
        "romaji":  "kōhī",
        "vietnamese_meaning":  "cà phê",
        "word_type":  "noun",
        "japanese_example":  "毎日コーヒーを飲みます。",
        "example_meaning":  "Mỗi ngày tôi uống cà phê.",
        "mnemonic_tip":  "Đồ uống",
        "image_url":  ""
    },
    {
        "id":  72,
        "lesson_id":  2,
        "hiragana":  "おみやげ",
        "romaji":  "omiyage",
        "vietnamese_meaning":  "quà lưu niệm",
        "word_type":  "noun",
        "japanese_example":  "これは日本のお土産です。",
        "example_meaning":  "Đây là quà lưu niệm Nhật Bản.",
        "mnemonic_tip":  "お土産 - Thổ sản",
        "image_url":  ""
    },
    {
        "id":  73,
        "lesson_id":  2,
        "hiragana":  "えいgo",
        "romaji":  "eigo",
        "vietnamese_meaning":  "tiếng Anh",
        "word_type":  "noun",
        "japanese_example":  "英語が văn ります。",
        "example_meaning":  "Tôi hiểu tiếng Anh.",
        "mnemonic_tip":  "英語 - Anh ngữ",
        "image_url":  ""
    },
    {
        "id":  74,
        "lesson_id":  2,
        "hiragana":  "にhonご",
        "romaji":  "nihongo",
        "vietnamese_meaning":  "tiếng Nhật",
        "word_type":  "noun",
        "japanese_example":  "日本語の勉強をします。",
        "example_meaning":  "Tôi học tiếng Nhật.",
        "mnemonic_tip":  "日本語 - Nhật Bản ngữ",
        "image_url":  ""
    },
    {
        "id":  75,
        "lesson_id":  2,
        "hiragana":  "なん",
        "romaji":  "nan",
        "vietnamese_meaning":  "cái gì",
        "word_type":  "noun",
        "japanese_example":  "これは何ですか。",
        "example_meaning":  "Đây là cái gì?",
        "mnemonic_tip":  "何 - Hà",
        "image_url":  ""
    }
];

const kanji = [
    {
        "id":  1,
        "lesson_id":  1,
        "character":  "私",
        "stroke_count":  "7",
        "onyomi":  "シ (shi)",
        "kunyomi":  "わたし (watashi)",
        "sino_vietnamese":  "TƯ",
        "vietnamese_meaning":  "Tôi, riêng tư",
        "mnemonic_tip":  "Mẹo nhớ: Bên trái là cây lúa (禾), bên phải là bộ khư (厶 - riêng tư). Lúa của riêng tôi.",
        "compounds":  "私 (わたし): Tôi; 私立 (しりつ): Tư lập"
    },
    {
        "id":  2,
        "lesson_id":  1,
        "character":  "人",
        "stroke_count":  "2",
        "onyomi":  "ジン (jin), ニン (nin)",
        "kunyomi":  "ひと (hito)",
        "sino_vietnamese":  "NHÂN",
        "vietnamese_meaning":  "Người",
        "mnemonic_tip":  "Mẹo nhớ: Hình ảnh hai chân người đang đứng dang rộng trên đất.",
        "compounds":  "あの人 (あのひと): Người kia; 日本人 (nihonjin): Người Nhật"
    },
    {
        "id":  3,
        "lesson_id":  1,
        "character":  "先",
        "stroke_count":  "6",
        "onyomi":  "セン (sen)",
        "kunyomi":  "さき (saki)",
        "sino_vietnamese":  "TIÊN",
        "vietnamese_meaning":  "Trước, đi đầu",
        "mnemonic_tip":  "Mẹo nhớ: Đi bộ (bộ nhi ⼉ ở dưới) trên đất (bộ thổ 土 ở trên) thì phải đi Trước.",
        "compounds":  "先生 (せんせい): Giáo viên; 先月 (せんげつ): Tháng trước"
    },
    {
        "id":  4,
        "lesson_id":  1,
        "character":  "生",
        "stroke_count":  "5",
        "onyomi":  "セイ (sei), ショウ (shou)",
        "kunyomi":  "う.まれる (u.mareru)",
        "sino_vietnamese":  "SINH",
        "vietnamese_meaning":  "Sống, sinh ra, học sinh",
        "mnemonic_tip":  "Mẹo nhớ: Hình ảnh một mầm cây nhỏ sinh trưởng trồi lên từ mặt đất.",
        "compounds":  "学生 (がくせい): Học sinh; 先生 (せんせい): Giáo viên"
    },
    {
        "id":  5,
        "lesson_id":  1,
        "character":  "学",
        "stroke_count":  "8",
        "onyomi":  "ガク (gaku)",
        "kunyomi":  "まな.bu (mana.bu)",
        "sino_vietnamese":  "HỌC",
        "vietnamese_meaning":  "Học, học vấn, trường học",
        "mnemonic_tip":  "Mẹo nhớ: Đứa trẻ (子) ở dưới mái nhà (宀) đang học bài.",
        "compounds":  "学生 (がくせい): Học sinh; 大学 (daigaku): Đại học"
    },
    {
        "id":  6,
        "lesson_id":  1,
        "character":  "会",
        "stroke_count":  "6",
        "onyomi":  "カイ (kai), エ (e)",
        "kunyomi":  "あ.u (a.u)",
        "sino_vietnamese":  "HỘI",
        "vietnamese_meaning":  "Hội họp, gặp gỡ",
        "mnemonic_tip":  "Mẹo nhớ: 3 người (bộ nhân 人 và nhị 二) cùng gặp gỡ dưới một mái nhà.",
        "compounds":  "会社 (かいしゃ): Công ty; 会う (a.u): Gặp gỡ"
    },
    {
        "id":  7,
        "lesson_id":  1,
        "character":  "社",
        "stroke_count":  "7",
        "onyomi":  "シャ (sha)",
        "kunyomi":  "yashiro",
        "sino_vietnamese":  "XÃ",
        "vietnamese_meaning":  "Đền thờ, xã hội, công ty",
        "mnemonic_tip":  "Mẹo nhớ: Bộ thị (礻- thần linh) đứng cạnh bộ thổ (土 - đất đai) chỉ đền thờ đất đai công xã.",
        "compounds":  "会社員 (kaishain): Nhân viên công ty; 社会 (shakai): Xã hội"
    },
    {
        "id":  8,
        "lesson_id":  1,
        "character":  "員",
        "stroke_count":  "10",
        "onyomi":  "イン (in)",
        "kunyomi":  "-",
        "sino_vietnamese":  "VIÊN",
        "vietnamese_meaning":  "Thành viên, nhân viên",
        "mnemonic_tip":  "Mẹo nhớ: Miệng (口) của người làm việc quản lý tiền vỏ sò (貝 - bối) là nhân viên.",
        "compounds":  "会社員 (kaishain): Nhân viên công ty; 銀行員 (ginkouin): Nhân viên ngân hàng"
    },
    {
        "id":  9,
        "lesson_id":  1,
        "character":  "日",
        "stroke_count":  "4",
        "onyomi":  "ニチ (nichi), ジツ (jitsu)",
        "kunyomi":  "ひ (hi), か (ka)",
        "sino_vietnamese":  "NHẬT",
        "vietnamese_meaning":  "Ngày, mặt trời, nước Nhật",
        "mnemonic_tip":  "Mẹo nhớ: Hình vẽ mặt trời tròn trịa có một gạch ở giữa.",
        "compounds":  "日本 (にほん): Nhật Bản; 日曜日 (nichiyoubi): Chủ nhật"
    },
    {
        "id":  10,
        "lesson_id":  1,
        "character":  "本",
        "stroke_count":  "5",
        "onyomi":  "ホン (hon)",
        "kunyomi":  "moto",
        "sino_vietnamese":  "BẢN",
        "vietnamese_meaning":  "Sách, cội nguồn, bản chất",
        "mnemonic_tip":  "Mẹo nhớ: Chữ Mộc (木 - cây) thêm một gạch ngang ở gốc chỉ cội nguồn gốc rễ.",
        "compounds":  "本 (ほん): Sách; 日本 (にほん): Nhật Bản"
    },
    {
        "id":  11,
        "lesson_id":  1,
        "character":  "国",
        "stroke_count":  "8",
        "onyomi":  "コク (koku)",
        "kunyomi":  "くに (kuni)",
        "sino_vietnamese":  "QUỐC",
        "vietnamese_meaning":  "Đất nước, quốc gia",
        "mnemonic_tip":  "Mẹo nhớ: Viên ngọc quý (玉) được bao quanh bảo vệ bởi bốn bức tường thành (囗) là đất nước.",
        "compounds":  "外国人 (gaikokujin): Người nước ngoài; Quốc gia (kokka): Quốc gia"
    },
    {
        "id":  12,
        "lesson_id":  2,
        "character":  "本",
        "stroke_count":  "5",
        "onyomi":  "hon",
        "kunyomi":  "moto",
        "sino_vietnamese":  "Bản",
        "vietnamese_meaning":  "sách, gốc",
        "mnemonic_tip":  "Hình vẽ thân cây có vạch gốc rễ",
        "compounds":  "日本語 (にほんご): tiếng Nhật, 本 (ほん): sách"
    },
    {
        "id":  13,
        "lesson_id":  2,
        "character":  "辞",
        "stroke_count":  "13",
        "onyomi":  "ji",
        "kunyomi":  "ya(meru)",
        "sino_vietnamese":  "Từ",
        "vietnamese_meaning":  "từ điển, từ bỏ",
        "mnemonic_tip":  "Tay cầm chỉ nam từ biệt lời nói",
        "compounds":  "辞書 (じしょ): từ điển"
    },
    {
        "id":  14,
        "lesson_id":  2,
        "character":  "書",
        "stroke_count":  "10",
        "onyomi":  "sho",
        "kunyomi":  "ka(ku)",
        "sino_vietnamese":  "Thư",
        "vietnamese_meaning":  "viết, sách",
        "mnemonic_tip":  "Tay cầm bút viết lên trang giấy",
        "compounds":  "図書館 (としょかん): thư viện, 書く (かく): viết"
    },
    {
        "id":  15,
        "lesson_id":  2,
        "character":  "雑",
        "stroke_count":  "14",
        "onyomi":  "zatsu, zō",
        "kunyomi":  "(none)",
        "sino_vietnamese":  "Tạp",
        "vietnamese_meaning":  "tạp nham, pha trộn",
        "mnemonic_tip":  "Nhiều loài chim đậu trên cây tạo nên sự hỗn tạp",
        "compounds":  "雑誌 (ざっし): tạp chí, 複雑 (ふくざつ): phức tạp"
    },
    {
        "id":  16,
        "lesson_id":  2,
        "character":  "誌",
        "stroke_count":  "14",
        "onyomi":  "shi",
        "kunyomi":  "(none)",
        "sino_vietnamese":  "Chí",
        "vietnamese_meaning":  "tạp chí, ghi chép",
        "mnemonic_tip":  "Lời nói ghi nhớ ý chí để xuất bản chí",
        "compounds":  "雑誌 (ざっし): tạp chí, 日誌 (にっし): nhật ký"
    },
    {
        "id":  17,
        "lesson_id":  2,
        "character":  "新",
        "stroke_count":  "13",
        "onyomi":  "shin",
        "kunyomi":  "atara(shii)",
        "sino_vietnamese":  "Tân",
        "vietnamese_meaning":  "mới",
        "mnemonic_tip":  "Cầm rìu đốn củi trên cây làm nên điều mới mẻ",
        "compounds":  "新聞 (しんぶん): báo, 新しい (あたらしい): mới"
    },
    {
        "id":  18,
        "lesson_id":  2,
        "character":  "聞",
        "stroke_count":  "14",
        "onyomi":  "bun, mon",
        "kunyomi":  "ki(ku)",
        "sino_vietnamese":  "Văn",
        "vietnamese_meaning":  "nghe, hỏi",
        "mnemonic_tip":  "Đứng ở cổng ghé tai nghe ngóng tin tức",
        "compounds":  "新聞 (しんぶん): báo, 聞く (きu): nghe"
    },
    {
        "id":  19,
        "lesson_id":  2,
        "character":  "鍵",
        "stroke_count":  "17",
        "onyomi":  "ken",
        "kunyomi":  "kagi",
        "sino_vietnamese":  "Kiện",
        "vietnamese_meaning":  "chìa khóa",
        "mnemonic_tip":  "Thanh kim loại dựng đứng mở cửa then chốt",
        "compounds":  "鍵 (かぎ): chìa khóa"
    },
    {
        "id":  20,
        "lesson_id":  2,
        "character":  "時",
        "stroke_count":  "10",
        "onyomi":  "ji",
        "kunyomi":  "toki",
        "sino_vietnamese":  "Thời",
        "vietnamese_meaning":  "thời gian, giờ",
        "mnemonic_tip":  "Mặt trời chiếu sáng ngôi chùa đo thời gian",
        "compounds":  "時計 (とけい): đồng hồ, 時間 (じかん): thời gian"
    },
    {
        "id":  21,
        "lesson_id":  2,
        "character":  "計",
        "stroke_count":  "9",
        "onyomi":  "kei",
        "kunyomi":  "haka(ru)",
        "sino_vietnamese":  "Kế",
        "vietnamese_meaning":  "kế hoạch, đo lường",
        "mnemonic_tip":  "Lời nói đếm từ một đến mười là kế hoạch",
        "compounds":  "時計 (とけい): đồng hồ, 計画 (けいかく): kế hoạch"
    },
    {
        "id":  22,
        "lesson_id":  2,
        "character":  "傘",
        "stroke_count":  "12",
        "onyomi":  "san",
        "kunyomi":  "kasa",
        "sino_vietnamese":  "Tản",
        "vietnamese_meaning":  "cái ô, cái dù",
        "mnemonic_tip":  "Hình vẽ cái ô che cho bốn người",
        "compounds":  "傘 (kasa): cái ô/dù"
    },
    {
        "id":  23,
        "lesson_id":  2,
        "character":  "車",
        "stroke_count":  "7",
        "onyomi":  "sha",
        "kunyomi":  "kuruma",
        "sino_vietnamese":  "Xa",
        "vietnamese_meaning":  "xe cộ, ô tô",
        "mnemonic_tip":  "Hình vẽ chiếc xe kéo nhìn từ trên xuống",
        "compounds":  "自動車 (じどうsha): ô tô, 電車 (でんしゃ): tàu điện"
    },
    {
        "id":  24,
        "lesson_id":  2,
        "character":  "机",
        "stroke_count":  "6",
        "onyomi":  "ki",
        "kunyomi":  "tsukue",
        "sino_vietnamese":  "Kỷ",
        "vietnamese_meaning":  "cái bàn",
        "mnemonic_tip":  "Mảnh gỗ có chân kê làm bàn viết",
        "compounds":  "机 (つくえ): cái bàn"
    },
    {
        "id":  25,
        "lesson_id":  2,
        "character":  "語",
        "stroke_count":  "14",
        "onyomi":  "go",
        "kunyomi":  "kata(ru)",
        "sino_vietnamese":  "Ngữ",
        "vietnamese_meaning":  "ngôn ngữ, kể",
        "mnemonic_tip":  "Năm người mở miệng cùng nói ra ngôn ngữ",
        "compounds":  "日本語 (にほんご): tiếng Nhật, 英語 (えいご): tiếng Anh"
    },
    {
        "id":  26,
        "lesson_id":  2,
        "character":  "何",
        "stroke_count":  "7",
        "onyomi":  "ka",
        "kunyomi":  "nani, nan",
        "sino_vietnamese":  "Hà",
        "vietnamese_meaning":  "cái gì",
        "mnemonic_tip":  "Người vác hành lý hỏi cái gì thế",
        "compounds":  "何 (なに): cái gì"
    }
];

const grammar = [
    {
        "id":  1,
        "lesson_id":  1,
        "title":  "N1 は N2 です",
        "meaning":  "N1 là N2",
        "structure":  "Danh từ 1 + は (wa) + Danh từ 2 + です",
        "vietnamese_explanation":  "Mẫu câu khẳng định cơ bản nhất, dùng 100% khi giới thiệu thông tin cá nhân.",
        "japanese_example":  "わたしは マイク・ミラー です。",
        "example_meaning":  "Tôi là Mike Miller.",
        "notes":  "🔊 Nghe"
    },
    {
        "id":  2,
        "lesson_id":  1,
        "title":  "N1 は N2 じゃありません",
        "meaning":  "N1 không phải là N2",
        "structure":  "Danh từ 1 + は + Danh từ 2 + じゃありません / では ありません",
        "vietnamese_explanation":  "Mẫu câu phủ định cơ bản của danh từ, sử dụng liên tục trong đời sống.",
        "japanese_example":  "サントスさんは 学生 じゃありません。",
        "example_meaning":  "Anh Santos không phải là sinh viên.",
        "notes":  "🔊 Nghe"
    },
    {
        "id":  3,
        "lesson_id":  1,
        "title":  "N1 は N2 ですか",
        "meaning":  "N1 có phải là N2 không?",
        "structure":  "Danh từ 1 + は + Danh từ 2 + ですか",
        "vietnamese_explanation":  "Dùng để xác nhận thông tin của người đối diện, cấu trúc hỏi đáp sơ cấp điển hình.",
        "japanese_example":  "ミラーさんは 会社員 ですか。",
        "example_meaning":  "Anh Miller có phải là nhân viên công ty không?",
        "notes":  "🔊 Nghe"
    },
    {
        "id":  4,
        "lesson_id":  1,
        "title":  "N1 も N2 です",
        "meaning":  "N1 cũng là N2",
        "structure":  "Danh từ 1 + も + Danh từ 2 + です",
        "vietnamese_explanation":  "Ứng dụng rất cao khi nói về sự giống nhau giữa các đối tượng trong hội thoại nhóm.",
        "japanese_example":  "わたしも 会社員 です。",
        "example_meaning":  "Tôi cũng là nhân viên công ty.",
        "notes":  "🔊 Nghe"
    },
    {
        "id":  5,
        "lesson_id":  1,
        "title":  "N1 の N2",
        "meaning":  "N2 của N1 / N2 thuộc N1",
        "structure":  "Danh từ 1 + の + Danh từ 2",
        "vietnamese_explanation":  "Mẫu câu nối danh từ cốt lõi, dùng khi giới thiệu công ty hoặc trường học sở tại của mình.",
        "japanese_example":  "わたしは IMCの 社員 です。",
        "example_meaning":  "Tôi là nhân viên của công ty IMC.",
        "notes":  "🔊 Nghe"
    },
    {
        "id":  6,
        "lesson_id":  2,
        "title":  "これ/それ/あれ は [N] です",
        "meaning":  "Đây/Đó/Kia là N",
        "structure":  "これ/それ/あれ + は + Danh từ + です",
        "vietnamese_explanation":  "Dùng để chỉ vật dựa vào khoảng cách tới người nói và người nghe. \u0027これ\u0027 chỉ vật gần người nói, \u0027それ\u0027 chỉ vật gần người nghe, \u0027あれ\u0027 chỉ vật xa cả hai.",
        "japanese_example":  "これは私のノートです。",
        "example_meaning":  "Đây là vở của tôi.",
        "notes":  "🔊 Nghe"
    },
    {
        "id":  7,
        "lesson_id":  2,
        "title":  "この/その/あの [N] は [A/N] です",
        "meaning":  "[N] này/đó/kia thì...",
        "structure":  "この/その/あの + Danh từ + は + Danh từ/Tính từ + です",
        "vietnamese_explanation":  "Chỉ định từ đi trực tiếp trước danh từ để bổ nghĩa. \u0027この\u0027 chỉ vật gần người nói, \u0027その\u0027 chỉ vật gần người nghe, \u0027あの\u0027 chỉ vật xa cả hai.",
        "japanese_example":  "この傘は私のです。",
        "example_meaning":  "Cái ô này là của tôi.",
        "notes":  "🔊 Nghe"
    },
    {
        "id":  8,
        "lesson_id":  2,
        "title":  "そうです / そうじゃありません",
        "meaning":  "Đúng thế / Không phải thế",
        "structure":  "そうです / そうじゃありません (hoặc そうではありません)",
        "vietnamese_explanation":  "Dùng trong câu trả lời xác nhận cho câu hỏi danh từ dạng \u0027[N1] は [N2] ですか\u0027.",
        "japanese_example":  "それは辞書ですか。はい、そうです。",
        "example_meaning":  "Đó là từ điển phải không? Vâng, đúng thế.",
        "notes":  "🔊 Nghe"
    },
    {
        "id":  9,
        "lesson_id":  2,
        "title":  "そうですか",
        "meaning":  "Thế à / Vậy à",
        "structure":  "そう + です + か",
        "vietnamese_explanation":  "Dùng khi người nói tiếp nhận thông tin mới từ người đối thoại, thể hiện thái độ hiểu ra vấn đề.",
        "japanese_example":  "これはベトナムのお土産です。そうですか。ありがとうございます。",
        "example_meaning":  "Đây là quà lưu niệm từ Việt Nam. Thế à. Cảm ơn bạn.",
        "notes":  "#VALUE!"
    },
    {
        "id":  10,
        "lesson_id":  2,
        "title":  "Câu 1 か、Câu 2 か",
        "meaning":  "C1 hay là C2? (Câu hỏi chọn lựa)",
        "structure":  "[C1] か、[C2] か",
        "vietnamese_explanation":  "Dùng khi người nói phân vân giữa hai hoặc nhiều lựa chọn, người trả lời sẽ chọn một trong các phương án chứ không trả lời hai hay không.",
        "japanese_example":  "これは「９」ですか、「７」ですか。ー「９」es。",
        "example_meaning":  "Đây là số 9 hay số 7? - Là số 9.",
        "notes":  "#VALUE!"
    },
    {
        "id":  11,
        "lesson_id":  2,
        "title":  "[N1] の [N2]",
        "meaning":  "N2 của N1 / N2 về N1",
        "structure":  "[N1] + の + [N2]",
        "vietnamese_explanation":  "Trợ từ の diễn tả mối quan hệ sở hữu (N2 thuộc về N1) hoặc chỉ nội dung, tính chất của N2 (N2 nói về nội dung gì của N1).",
        "japanese_example":  "これは日本語の教科書です。",
        "example_meaning":  "Đây là sách giáo khoa tiếng Nhật.",
        "notes":  "🔊 Nghe"
    }
];

const kaiwaDialog = [
    {
        "id":  1,
        "lesson_id":  1,
        "topic":  "Hội thoại 1: Chào hỏi lần đầu gặp gỡ",
        "speaker":  "ナム",
        "japanese":  "初めまして。私は ナム です。ベトナム から来ました。どうぞよろしく。",
        "romaji":  "Hajimemashite. Watashi wa Namu desu. Betonamu kara kimashita. Dōzo yoroshiku.",
        "vietnamese":  "Rất vui được gặp bạn. Tôi là ナム. Tôi đến từ ベトナム. Rất mong được giúp đỡ."
    },
    {
        "id":  2,
        "lesson_id":  1,
        "topic":  "Hội thoại 1: Chào hỏi lần đầu gặp gỡ",
        "speaker":  "ミラー",
        "japanese":  "初めまして。ミラー です。アメリカ から来ました。こちらこそどうぞよろしく。",
        "romaji":  "Hajimemashite. Mirā desu. Amerika kara kimashita. Kochira koso dōzo yoroshiku.",
        "vietnamese":  "Rất vui được gặp bạn. Tôi là Miller. Tôi đến từ Mỹ. Chính tôi mới là người cần giúp đỡ."
    },
    {
        "id":  3,
        "lesson_id":  1,
        "topic":  "Hội thoại 2: Hỏi tuổi tác",
        "speaker":  "ナム",
        "japanese":  "失礼ですが、ミラーさんは おいくつ（何歳）ですか。",
        "romaji":  "Shitsurei desu ga, Mirā-san wa oikutsu (nansai) desu ka.",
        "vietnamese":  "Xin lỗi, anh Miller bao nhiêu tuổi ạ?"
    },
    {
        "id":  4,
        "lesson_id":  1,
        "topic":  "Hội thoại 2: Hỏi tuổi tác",
        "speaker":  "ミラー",
        "japanese":  "私は 30歳 です。ナムさんは？",
        "romaji":  "Watashi wa 30-sai desu. Namu-san wa?",
        "vietnamese":  "Tôi 30 tuổi. Còn anh ナム?"
    },
    {
        "id":  5,
        "lesson_id":  1,
        "topic":  "Hội thoại 2: Hỏi tuổi tác",
        "speaker":  "ナム",
        "japanese":  "私は 22歳 です。",
        "romaji":  "Watashi wa 22-sai desu.",
        "vietnamese":  "Tôi 22 tuổi."
    },
    {
        "id":  6,
        "lesson_id":  1,
        "topic":  "Hội thoại 3: Hỏi nghề nghiệp",
        "speaker":  "ミラー",
        "japanese":  "ナムさんは 学生 ですか。",
        "romaji":  "Namu-san wa gakusei desu ka.",
        "vietnamese":  "Anh ナム là học sinh phải không?"
    },
    {
        "id":  7,
        "lesson_id":  1,
        "topic":  "Hội thoại 3: Hỏi nghề nghiệp",
        "speaker":  "ナム",
        "japanese":  "いいえ、私は 学生 じゃありません。エンジニア です。FPT の社員です。",
        "romaji":  "Iie, watashi wa gakusei ja arimasen. enjinia desu. FPT no shain desu.",
        "vietnamese":  "Không, tôi không phải học sinh. Tôi là エンジニア. Tôi là nhân viên của FPT."
    },
    {
        "id":  8,
        "lesson_id":  1,
        "topic":  "Hội thoại 3: Hỏi nghề nghiệp",
        "speaker":  "ミラー",
        "japanese":  "そうですか。私も 会社員 です。 IMC の社員です。",
        "romaji":  "Sō desu ka. Watashi mo kaishain desu. IMC no shain desu.",
        "vietnamese":  "Thế à. Tôi cũng là nhân viên công ty. Tôi là nhân viên của IMC."
    },
    {
        "id":  9,
        "lesson_id":  1,
        "topic":  "Hội thoại 4: Giới thiệu người thứ ba",
        "speaker":  "ナム",
        "japanese":  "あの人は どなた ですか。",
        "romaji":  "Ano hito wa donata desu ka.",
        "vietnamese":  "Người kia là vị nào vậy?"
    },
    {
        "id":  10,
        "lesson_id":  1,
        "topic":  "Hội thoại 4: Giới thiệu người thứ ba",
        "speaker":  "ミラー",
        "japanese":  "あの人は サントスさん です。ブラジル人 です。",
        "romaji":  "Ano hito wa Santosu-san desu. Burajiru-jin desu.",
        "vietnamese":  "Người kia là anh Santos. Anh ấy là người Brazil."
    },
    {
        "id":  11,
        "lesson_id":  1,
        "topic":  "Hội thoại 5: Chào hỏi tạm biệt xã giao",
        "speaker":  "ミラー",
        "japanese":  "お名前は何ですか。",
        "romaji":  "O-namae wa nan desu ka.",
        "vietnamese":  "Tên của bạn là gì?"
    },
    {
        "id":  12,
        "lesson_id":  1,
        "topic":  "Hội thoại 5: Chào hỏi tạm biệt xã giao",
        "speaker":  "ナム",
        "japanese":  "私は ナム です。これからお世話になります。よろしくおねがいします。",
        "romaji":  "Watashi wa Namu desu. Korekara o-sewa ni narimasu. Yoroshiku onegaishimasu.",
        "vietnamese":  "Tôi là ナム. Từ nay mong nhận được sự giúp đỡ. Xin cảm ơn."
    },
    {
        "id":  13,
        "lesson_id":  1,
        "topic":  "Hội thoại 5: Chào hỏi tạm biệt xã giao",
        "speaker":  "ミラー",
        "japanese":  "こちらこそ、よろしく。",
        "romaji":  "Kochira koso, yoroshiku.",
        "vietnamese":  "Chính tôi cũng vậy, xin cảm ơn."
    },
    {
        "id":  14,
        "lesson_id":  2,
        "topic":  "Hội thoại 1: Tặng quà lưu niệm (Omiyage)",
        "speaker":  "サントス",
        "japanese":  "はい、ナム さん。これはお土産です。どうぞ。",
        "romaji":  "Hai, Namu-san. Kore wa o-miyage desu. Dōzo.",
        "vietnamese":  "Vâng, anh ナム. Đây là quà lưu niệm. Xin mời."
    },
    {
        "id":  15,
        "lesson_id":  2,
        "topic":  "Hội thoại 1: Tặng quà lưu niệm (Omiyage)",
        "speaker":  "ナム",
        "japanese":  "あ、ありがとうございます。こちらは何ですか。",
        "romaji":  "A, arigatō gozaimasu. Kore wa nan desu ka.",
        "vietnamese":  "A, xin cảm ơn rất nhiều. Đây là cái gì thế?"
    },
    {
        "id":  16,
        "lesson_id":  2,
        "topic":  "Hội thoại 1: Tặng quà lưu niệm (Omiyage)",
        "speaker":  "サントス",
        "japanese":  "チョコレートです。日本語で「チョコレート」ですよ。どうぞ。",
        "romaji":  "Chokorēto desu. Nihongo de \"Chokorēto\" desu yo. Dōzo.",
        "vietnamese":  "Sô-cô-la đấy. Trong tiếng Nhật gọi là \"chokore-to\" đấy. Mời anh/chị."
    },
    {
        "id":  17,
        "lesson_id":  2,
        "topic":  "Hội thoại 1: Tặng quà lưu niệm (Omiyage)",
        "speaker":  "ナム",
        "japanese":  "そうですか。どうもありがとうございます。",
        "romaji":  "Sō desu ka. Dōmo arigatō gozaimasu.",
        "vietnamese":  "Thế à. Xin cảm ơn rất nhiều."
    },
    {
        "id":  18,
        "lesson_id":  2,
        "topic":  "Hội thoại 2: Hỏi về đồ vật xung quanh (Cái này/đó/kia)",
        "speaker":  "ナム",
        "japanese":  "それは何ですか。",
        "romaji":  "Sore wa nan desu ka.",
        "vietnamese":  "Cái đó là cái gì thế?"
    },
    {
        "id":  19,
        "lesson_id":  2,
        "topic":  "Hội thoại 2: Hỏi về đồ vật xung quanh (Cái này/đó/kia)",
        "speaker":  "サントス",
        "japanese":  "これは雑誌です。自動車の雑誌です。",
        "romaji":  "Kore wa zasshi desu. Jidōsha no zasshi desu.",
        "vietnamese":  "Đây là tạp chí. Tạp chí về ô tô."
    },
    {
        "id":  20,
        "lesson_id":  2,
        "topic":  "Hội thoại 2: Hỏi về đồ vật xung quanh (Cái này/đó/kia)",
        "speaker":  "ナム",
        "japanese":  "あれは何ですか。",
        "romaji":  "Are wa nan desu ka.",
        "vietnamese":  "Cái kia là cái gì thế?"
    },
    {
        "id":  21,
        "lesson_id":  2,
        "topic":  "Hội thoại 2: Hỏi về đồ vật xung quanh (Cái này/đó/kia)",
        "speaker":  "サントス",
        "japanese":  "あれはテレビです。新しいテレビですよ。",
        "romaji":  "Are wa terebi desu. Atarashii terebi desu yo.",
        "vietnamese":  "Cái kia là tivi. Tivi mới đấy."
    },
    {
        "id":  22,
        "lesson_id":  2,
        "topic":  "Hội thoại 3: Hỏi về sở hữu đồ vật",
        "speaker":  "サントス",
        "japanese":  "この鍵は ナム さんのですか。",
        "romaji":  "Kono kagi wa Namu-san no desu ka.",
        "vietnamese":  "Chiếc chìa khóa này là của anh ナム phải không?"
    },
    {
        "id":  23,
        "lesson_id":  2,
        "topic":  "Hội thoại 3: Hỏi về sở hữu đồ vật",
        "speaker":  "ナム",
        "japanese":  "いいえ、違います。あれはミラーさんのですよ。",
        "romaji":  "Iie, chigaimasu. Are wa Mirā-san no desu yo.",
        "vietnamese":  "Không, không phải. Kia là của anh Miller đấy."
    },
    {
        "id":  24,
        "lesson_id":  2,
        "topic":  "Hội thoại 4: Hỏi về sách giáo khoa tiếng Nhật",
        "speaker":  "ナム",
        "japanese":  "これは日本語ของ教科書ですか。",
        "romaji":  "Kore wa nihongo no kyōkasho desu ka.",
        "vietnamese":  "Đây là sách giáo khoa tiếng Nhật phải không?"
    },
    {
        "id":  25,
        "lesson_id":  2,
        "topic":  "Hội thoại 4: Hỏi về sách giáo khoa tiếng Nhật",
        "speaker":  "サントス",
        "japanese":  "いいえ、違います。英語の教科書です。",
        "romaji":  "Iie, chigaimasu. Eigo no kyōkasho desu.",
        "vietnamese":  "Không, không phải. Đó là sách giáo khoa tiếng Anh."
    },
    {
        "id":  26,
        "lesson_id":  2,
        "topic":  "Hội thoại 4: Hỏi về sách giáo khoa tiếng Nhật",
        "speaker":  "ナム",
        "japanese":  "この本は誰のですか。",
        "romaji":  "Kono hon wa dare no desu ka.",
        "vietnamese":  "Quyển sách này là của ai?"
    },
    {
        "id":  27,
        "lesson_id":  2,
        "topic":  "Hội thoại 4: Hỏi về sách giáo khoa tiếng Nhật",
        "speaker":  "サントス",
        "japanese":  "それは私の本です。",
        "romaji":  "Sore wa watashi no hon desu.",
        "vietnamese":  "Đó là sách của tôi."
    },
    {
        "id":  28,
        "lesson_id":  2,
        "topic":  "Hội thoại 5: Xác nhận đồ vật bị bỏ quên",
        "speaker":  "ナム",
        "japanese":  "この傘はあなたのですか。",
        "romaji":  "Kono kasa wa anata no desu ka.",
        "vietnamese":  "Cái ô này là của bạn phải không?"
    },
    {
        "id":  29,
        "lesson_id":  2,
        "topic":  "Hội thoại 5: Xác nhận đồ vật bị bỏ quên",
        "speaker":  "サントス",
        "japanese":  "はい、私のです。どうもありがとうございました。",
        "romaji":  "Hai, watashi no desu. Dōmo arigatō gozaimashita.",
        "vietnamese":  "Vâng, của tôi đấy. Xin cảm ơn bạn rất nhiều."
    },
    {
        "id":  30,
        "lesson_id":  2,
        "topic":  "Hội thoại 5: Xác nhận đồ vật bị bỏ quên",
        "speaker":  "ナム",
        "japanese":  "いいえ、どういたしまして。",
        "romaji":  "Iie, dōitashimashite.",
        "vietnamese":  "Không có gì."
    }
];

const students = [
  { 
    id: 'user123', 
    email: 'user@nihongoflow.com', 
    display_name: 'H\u1ecdc Vi\u00ean A', 
    created_at: new Date().toISOString() 
  }
];

// In-memory store for user progress: key is "userId:itemType:itemId" -> status
const userProgress = {
  "user123:vocabulary:1": "mastered",
  "user123:vocabulary:2": "mastered",
  "user123:vocabulary:3": "mastered",
  "user123:vocabulary:4": "mastered",
  "user123:vocabulary:5": "mastered",
  "user123:vocabulary:6": "learning",
  "user123:vocabulary:7": "learning",
  "user123:vocabulary:8": "learning",
  "user123:kanji:1": "mastered",
  "user123:kanji:2": "mastered",
  "user123:kanji:3": "learning"
};

// In-memory store for target plans: key is userId -> targetPlanObject
const targetPlan = {
  "user123": {
    user_id: "user123",
    start_date: "2026-06-13",
    end_date: "2026-06-20",
    vocabulary_target: 30,
    kanji_target: 10,
    self_evaluation: "T\u1ed1t",
    updated_at: new Date().toISOString()
  }
};

module.exports = {
  lessons,
  vocabulary,
  kanji,
  grammar,
  kaiwaDialog,
  students,
  userProgress,
  targetPlan
};
